"""Build the paper table and the full machine-readable table from data/*.json.

    python scripts/make_tables.py [--top 25]

Writes tables/survey_main.tex, a booktabs table sized for a paper column, and
tables/survey_full.csv, every row and every column for the appendix and for reuse.

The LaTeX table deliberately reports the estimate's provenance in its own column. A number whose
source is 'resampled' is a floor, not a measurement, and a reader who cannot see which is which
will read the two as equivalent.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, HERE)

from hidden_info_survey.catalog import FAMILIES  # noqa: E402

SOURCE_SHORT = {"exact": "exact", "closed form": "closed", "resampled": "floor", "not measured": "—"}


def load_rows(data_dir):
    rows = []
    for name in ("openspiel.json", "rlcard.json"):
        path = os.path.join(data_dir, name)
        if os.path.exists(path):
            rows += json.load(open(path))["rows"]

    out = []
    for row in rows:
        if "error" in row:
            continue
        for key, source in (
            ("bits_exact", "exact"),
            ("bits_closed_form", "closed form"),
            ("bits_resampled", "resampled"),
        ):
            if row.get(key) is not None:
                row["bits"], row["bits_source"] = row[key], source
                break
        else:
            row["bits"], row["bits_source"] = None, "not measured"
        out.append(row)
    return out


def escape(text):
    return str(text).replace("&", r"\&").replace("_", r"\_").replace("%", r"\%")


def write_latex(rows, path, top):
    ranked = sorted(
        [r for r in rows if r["bits"] is not None], key=lambda r: r["bits"], reverse=True
    )[:top]

    lines = [
        "% generated by scripts/make_tables.py -- do not edit by hand",
        r"\begin{tabular}{l r l r r r r}",
        r"\toprule",
        r"Game & Bits & Source & Actions & Legal & Input & Turns \\",
        r"\midrule",
    ]
    for row in ranked:
        legal = "—" if row["branch_mean"] is None else f"{row['branch_mean']:.0f}"
        turns = "—" if row["len_mean"] is None else f"{row['len_mean']:.0f}"
        # A few games declare a placeholder tensor rather than a real one; OpenSpiel's cribbage
        # reports size 1. That is a missing observation, not a tiny one, and printing the 1 invites
        # a reader to believe it. Same threshold the scatter uses.
        size = "—" if (row.get("input_size") or 0) < 8 else f"{row['input_size']}"
        lines.append(
            f"{escape(row['label'])} & {row['bits']:.1f} & {SOURCE_SHORT[row['bits_source']]} & "
            f"{row['actions_declared']} & {legal} & {size} & {turns} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]

    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  wrote {path}  ({len(ranked)} rows)")


def write_family_latex(rows, path):
    """Per-family summary: the analysis a 90-row ranking cannot show.

    Median rather than mean, because Mahjong at 163 bits would drag any family mean it sits in.
    The "measured" column matters as much as the bits: it says how much of a family we can put a
    number on at all, which is the honest way to report that fog-of-war games are a blind spot.
    """
    from statistics import median
    order = ["card", "dial", "multi", "dice", "comm", "board", "solo"]
    lines = [
        "% generated by scripts/make_tables.py -- do not edit by hand",
        r"\begin{tabular}{l r r r l}",
        r"\toprule",
        r"Family & Games & Measured & Median bits & Range \\",
        r"\midrule",
    ]
    for fam in order:
        group = [r for r in rows if r["family"] == fam]
        if not group:
            continue
        bits = [r["bits"] for r in group if r["bits"] is not None]
        if bits:
            rng = f"{min(bits):.1f} to {max(bits):.1f}"
            med = f"{median(bits):.1f}"
        else:
            rng, med = "---", "---"
        lines.append(f"{FAMILIES[fam]} & {len(group)} & {len(bits)} & {med} & {rng} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  wrote {path}")


def write_csv(rows, path):
    columns = [
        "label", "game", "engine", "family", "players", "bits", "bits_source",
        "bits_exact", "bits_closed_form", "bits_resampled", "resample_censored_frac",
        "actions_declared", "branch_mean", "branch_max", "input_size", "len_mean",
        "maxlen_declared", "information", "dynamics", "chance", "hidden_note", "seconds",
    ]
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=columns, extrasaction="ignore")
        writer.writeheader()
        for row in sorted(rows, key=lambda r: (r["bits"] is None, -(r["bits"] or 0))):
            writer.writerow(row)
    print(f"  wrote {path}  ({len(rows)} rows)")


def summarise(rows):
    """The handful of numbers the paper's prose quotes, printed so they can be checked."""
    measured = [r for r in rows if r["bits"] is not None]
    anchor = next((r for r in rows if r["label"] == "Gin rummy (standard)"), None)
    print("\nsummary")
    print(f"  games measured          {len(rows)}")
    print(f"  with a hidden number    {len(measured)}")
    for family, label in FAMILIES.items():
        n = sum(1 for r in rows if r["family"] == family)
        if n:
            print(f"    {label:26s} {n}")
    by_source = {}
    for r in measured:
        by_source[r["bits_source"]] = by_source.get(r["bits_source"], 0) + 1
    print(f"  estimate provenance     {by_source}")
    if anchor:
        above = [
            r for r in measured
            if r["players"] == 2 and r["bits"] > anchor["bits"] and r["label"] != anchor["label"]
        ]
        print(f"  anchor (gin rummy)      {anchor['bits']} bits")
        print(f"  two-player games above  {[(r['label'], r['bits']) for r in above]}")
    saturated = [r for r in measured if r["bits_source"] == "resampled"]
    print(f"  resampled floors        {[(r['label'], r['bits']) for r in saturated]}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--top", type=int, default=25)
    args = ap.parse_args()

    rows = load_rows(os.path.join(HERE, "data"))
    write_latex(rows, os.path.join(HERE, "tables", "survey_main.tex"), args.top)
    write_family_latex(rows, os.path.join(HERE, "tables", "survey_families.tex"))
    write_csv(rows, os.path.join(HERE, "tables", "survey_full.csv"))
    summarise(rows)
    return 0


if __name__ == "__main__":
    sys.exit(main())
