"""Build the probe-summary table from data/probes.json.

    python scripts/make_tables.py

One table, three rows, one per probe: the question it asks, the number it produced, and the verdict
that number licenses. A reader who reads only this table should be able to state the paper's
conclusion, which is the job a summary table is actually for.
"""

from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    with open(os.path.join(HERE, "data", "probes.json")) as f:
        p = json.load(f)

    cap = p["capacity"]
    voi = p["value_of_information"]
    orc = p["oracle_observation"]
    arms = {a["label"]: a for a in orc["arms"]}
    base = arms["Baseline (4 planes)"]
    oracle = arms["Oracle observation (5 planes)"]

    rows = [
        ("Capacity",
         "is the network the limit?",
         f"every encoder in {cap['band_lo']*100:.1f}--{cap['band_hi']*100:.1f}",
         "no"),
        ("Value of information",
         "what is the hidden state worth, at most?",
         f"fair {voi['fair_range'][0]*100:.1f}--{voi['fair_range'][1]*100:.1f} vs "
         f"oracle {voi['oracle_range'][0]*100:.1f}--{voi['oracle_range'][1]*100:.1f}",
         "upper bound only"),
        ("Oracle observation",
         "information-bound or learning-bound?",
         f"{oracle['mean']*100:.1f} vs {base['mean']*100:.1f} baseline",
         "no benefit detected"),
    ]

    lines = [
        "% generated by scripts/make_tables.py -- do not edit by hand",
        r"\begin{tabular}{l l l l}",
        r"\toprule",
        r"Probe & Question & Measured (\% vs the expert) & Verdict \\",
        r"\midrule",
    ]
    for name, q, measured, verdict in rows:
        lines.append(f"{name} & {q} & {measured} & {verdict} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]

    out = os.path.join(HERE, "tables", "probes.tex")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  wrote {out}")
    for r in rows:
        print(f"   {r[0]:22s} {r[2]:38s} -> {r[3]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
