"""Build the probe-summary table from data/probes.json.

    python scripts/probe_tables.py

One table, three rows, one per probe: the question it asks, the number it produced, and the verdict
that number licenses. A reader who reads only this table should be able to state the paper's
conclusion, which is the job a summary table is actually for.
"""

from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import gin_arms


def main():
    with open(os.path.join(HERE, "data", "probes.json")) as f:
        p = json.load(f)

    cap = p["capacity"]
    voi = p["value_of_information"]
    orc = p["oracle_observation"]
    live = gin_arms.arms()
    orc_vs_base = gin_arms.contrast("oracle", "baseline")
    orc_vs_plac = gin_arms.contrast("oracle", "placebo")

    # Every row fits one line. Two-line rows made the table hard to track: the eye lost which
    # question belonged to which verdict, and an indented sub-row did not line up with the column
    # above it. The full means live in Figure 2 and Appendix I, so this table carries the contrast.
    rows = [
        ("Architecture sensitivity", "do the encoders differ?",
         f"all in {cap['band_lo']*100:.1f} to {cap['band_hi']*100:.1f}", "none tested wins"),
        ("Oracle-search gap", "what does privileged state buy?",
         f"{voi['fair_range'][0]*100:.1f} to {voi['fair_range'][1]*100:.1f} vs "
         f"{voi['oracle_range'][0]*100:.1f} to {voi['oracle_range'][1]*100:.1f}",
         "confounded proxy"),
        ("Oracle observation", "does the raw hidden hand help?",
         f"{orc_vs_base['diff']:+.2f} "
         f"[{orc_vs_base['lo']:+.2f}, {orc_vs_base['hi']:+.2f}]", "no detectable gain"),
        ("Oracle against placebo", "is any of it the wider input?",
         f"{orc_vs_plac['diff']:+.2f} "
         f"[{orc_vs_plac['lo']:+.2f}, {orc_vs_plac['hi']:+.2f}]", "no detectable gain"),
    ]

    lines = [
        "% generated by scripts/probe_tables.py -- do not edit by hand",
        r"\begin{tabular}{@{}l l l l@{}}",
        r"\toprule",
        r"Probe & Question & Measured & Verdict \\",
        r"\midrule",
    ]
    for name, q, measured, verdict in rows:
        lines.append(f"{name} & {q} & {measured} & {verdict} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]

    out = os.path.join(HERE, "tables", "probes.tex")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  wrote {out}")
    for r in rows:
        print(f"   {r[0]:22s} {r[2]:38s} -> {r[3]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
